name: Script-Runner

on:
  workflow_dispatch:
    inputs:
      script:
        type: string
        required: true
      context:
        type: string
        required: true

jobs:
  run-script:
    name: Run Script
    runs-on: ubuntu-latest
    steps:
      - name: Run Script
        run: |
          script="${{ inputs.script }}"
          context="${{ inputs.context }}"
          eval "$script"